#!/usr/bin/env bash

# Exit on first failure.
set -e

# Exit on unset variable.
set -u

# Change directory to repository root.
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
readonly SCRIPT_DIR
cd "${SCRIPT_DIR}/.."

if [ $# -ne 0 ]; then
  printf '%s\n' 'Error: This script does not accept arguments'
  exit 2
fi

# Define the file path to sort
FILE_PATH='data/excludes.txt'
readonly FILE_PATH

TEMP_FILE=$(mktemp)
readonly TEMP_FILE

# Sort and deduplicate
cat "${FILE_PATH}" | sort | uniq > "${TEMP_FILE}"

# Compare files to see if content changed
if diff -q "${FILE_PATH}" "${TEMP_FILE}" > /dev/null; then
  CHANGED=0
else
  CHANGED=1
fi

# Update the excludes file
mv "${TEMP_FILE}" "${FILE_PATH}"

# Return non-zero if sorting changed the file
exit ${CHANGED}
